version: "3.5"

services:
  api01: &api
    # image: cristiano182/rinha-backend:latest
    restart: always
    build: .
    hostname: api01
    networks:
      - rinha-network
    environment:
      - MONGO_CONNECTION=mongodb://root:dbpass@mongodb:27017/?authMechanism=DEFAULT
      - PORT=3000
    depends_on:
      - mongodb
    ulimits:
        nproc: 1000000
        nofile:
          soft: 1000000
          hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"
  api02:
    <<: *api 
    hostname: api02
    environment:
     - PORT=3001
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "90MB"
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=dbpass
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_DISABLE_JAVASCRIPT=yes
      - MONGODB_DEFAULT_DISABLE_SYSTEM_LOG=true
    ports:
      - 27017:27017
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "400MB"
networks:
  rinha-network:
    driver: bridge